- Observability:
    - Grafana:
        href: http://localhost:32911/
    - Prometheus:
        href: http://localhost:52441/
    - Portainer:
        href: http://localhost:37017/
    - Dozzle:
        href: http://localhost:8833/
    - Adguard:
        href: http://localhost:3333/
    - SigNoz:
        href: http://localhost:3301/
- Code:
    - Github:
        href: https://github.com/marcelovicentegc/homeserver
