---
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  portainer-data:
    driver: local
services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.1.3
    container_name: grafana-homeserver
    ports:
      - 32911:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  prometheus:
    image: docker.io/prom/prometheus:v2.53.1
    container_name: prometheus-homeserver
    ports:
      - 52441:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
  portainer:
    container_name: portainer-homeserver
    image: docker.io/portainer/portainer-ce:latest
    ports:
      - 37017:9000
      - 48397:9443
      - 44653:8000
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter-homeserver
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-homeserver
    ports:
      - 3000:3000
    volumes:
      - ./config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle-homeserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8833:8080
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome-homeserver
    ports:
      # DNS Server enabled
      # DNS (https://www.speedguide.net/port.php?port=53)
      # - 53:53/tcp
      # - 53:53/udp
      # DNS over QUIC/TLS (https://www.speedguide.net/port.php?port=853)
      # - 853:853/tcp

      # Web Interface enabled
      - 3333:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
      # Unassigned port
      - 784:784/udp

      # DHCP Server enabled
      # DHCP (https://www.speedguide.net/port.php?port=67)
      # - 67:67/udp
      # - 68:68/udp
      # - 68:68/tcp
    volumes:
      - ./config/adguard/work:/opt/adguardhome/work
      - ./config/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
